name       : python-opengl
version    : 3.1.6
release    : 7
source     :
    - https://files.pythonhosted.org/packages/source/P/PyOpenGL/PyOpenGL-3.1.6.tar.gz : 8ea6c8773927eda7405bffc6f5bb93be81569a7b05c8cac50cd94e969dce5e27
homepage   : https://pyopengl.sourceforge.net/
license    : BSD-3-Clause
component  : programming.python
summary    : Standard OpenGL bindings for Python
description: |
    PyOpenGL is the most common cross platform Python binding to OpenGL and related APIs. The binding is created using the standard ctypes library, and is provided under an extremely liberal BSD-style Open-Source license.
builddeps  :
    - pkgconfig(python3)
build      : |
    %python3_setup
install    : |
    %python3_install
