name       : python-opengl
version    : 3.1.0
release    : 1
source     :
    - https://pypi.python.org/packages/9c/1d/4544708aaa89f26c97cc09450bb333a23724a320923e74d73e028b3560f9/PyOpenGL-3.1.0.tar.gz : 9b47c5c3a094fa518ca88aeed35ae75834d53e4285512c61879f67a48c94ddaf
license    : BSD-3-Clause
component  : programming.python
summary    : Standard OpenGL bindings for Python
description: |
    PyOpenGL is the most common cross platform Python binding to OpenGL and related APIs. 
    The binding is created using the standard ctypes library, and is provided under an extremely liberal BSD-style Open-Source license.
builddeps  :
    - pkgconfig(python-3.5)
    - python-setuptools
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install

